config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :pins do
    member do
      put "like", to: "pins#upvote"
      get "landing"
    end
  end

  root 'pins#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_for :admins, :controllers => { :registrations => "registrations" }

  match '/users',   to: 'users#index',   via: 'get'

  match '/users/:id',     to: 'users#show',       via: 'get'
  resources :users, :only =>[:show]

end

app/models/pin.rb
class Pin < ActiveRecord::Base

  scope :copyrighted, -> { where(copyrighted: true) }
  scope :pending_copyright, -> { where(pending_copyright: true) }

  validates :title, :description, presence: true
  acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300"}
  validates_attachment :image,
  :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"] }

  # It returns the pins whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%")
  end

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  state_machine :state, initial: :pending do
    after_transition vetting: :publish, do: :check_image_copyright

    event :process do
      transition pending: :vetting
    end

    event :failed do
      transition vetting: :failed
    end

    event :publish do
      transition vetting: :published
    end

    event :share do
      transition published: :shared
    end

  end

  def check_image_copyright
    if true
      share 
    else
      failed
    end
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show, :landing]

  # GET /pins
  # GET /pins.json
  def index
    if params[:search]
      @pins = Pin.search(params[:search]).order("created_at DESC")
    else
      @pins = Pin.where(pending_copyright: true)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @pins.as_csv}
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  def landing
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, :status)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= bootstrap_form_for (@pin), html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :image, as: :file %>
  </div>
  <div class="field">
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.select :status, ["Copyrighted", "Pending Copyright"] %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel panel-title">
      <h1>Editing Pin</h1>
    </div>
    <div class="panel panel-body">
      <%= image_tag @pin.image.url %>
      <%= render 'form' %>
    </div>
    <div class="panel panel-footer">
      <%= link_to 'Show', @pin %> |
      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<div id="pins" class="transition-enabled">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to image_tag pin.image.url %>
        <div class="panel-body">
          <%= link_to pin.title, pin_path(pin) %>
          <hr>
          <p>submitted by<%= pin.user.email %></p>
        </div>
        <% if user_signed_in? %>
        <%= link_to 'Edit', edit_pin_path(pin) %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/pins/landing.html.erb
<div class="container">
  <div id="landingimage"class="row">
    <h1> <%= link_to 'Checkout some awesome nature images', pins_path %> </h1>
  </div>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel panel-heading">
      <h1>New Pin</h1>
    </div>
    <div class="panel panel-body">
    <%= render 'form' %>
    </div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <p id="notice"><%= notice %></p>
          <div class="panel-heading pin_image">
        <p>
          <%= image_tag @pin.image.url(:medium) %>
        </p>
          </div>
          <div class="panel-body">
        <p>
          <strong>Title:</strong>
          <%= @pin.title %>
        </p>

        <p>
          <strong class="description">Description:</strong>
          <%= @pin.description %>
        </p>
          </div>
          <div class="panel-footer">
            <div class="row">
              <div class="col-md-6">
        <p>
          <strong>Created by</strong>
          <%= @pin.user.email %>
        </p>
              </div>
              <div class="col-md-6">
                <div class="btn pull-right">
                <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-heart">
                    <%= @pin.get_upvotes.size %>
                <% end %>
                <% if user_signed_in? %>
                <%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-default" %> |
                <%= link_to 'Back', pins_path, class: "btn btn-default"  %>
                <% end %>
                </div
              </div>
            </div>
          </div>


      </div>
  </div>
</div>