config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :pins do
    member do
      put "like", to: "pins#upvote"
      get "landing"
    end
  end

  root 'pins#landing'

  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_for :admins, :controllers => { :registrations => "registrations" }

  match '/users',   to: 'users#index',   via: 'get'

  match '/users/:id',     to: 'users#show',       via: 'get'
  resources :users, :only =>[:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="nav navbar navbar-default">
    <div class="container">
      <nav class="navbar-brand"><%= link_to "Natures @rt", root_path %></nav>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New pin", new_pin_path %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Users list", users_path %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up",  new_user_registration_path %></li>
          <li><%= link_to "Sign in",  new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </nav>

  <%= form_tag(pins_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "title" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn" type="submit">Search by Title: <i class="icon-search"></i></button>
    </div>
  <% end %>



<%= yield %>

</body>
</html>